Repository Coaktion/client-core, pull requests merged in 2023-05, with the labels that each got.

#30 fix(workflows): Ajustanto o pipeline de testes
  .github/workflows/test.yml
  package-lock.json
Labels: bugfix

#31 Release/v1.3.0
  .github/workflows/npm-publish.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#32 Release/v1.3.1
  .github/workflows/npm-publish.yml
  .github/workflows/test.yml
  .npmrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#34 fix: ajustando instanciacao classe Zendesk
  src/base.ts
  src/types.ts
  tests/zendesk.test.ts
Labels: bugfix

#37 ci(github): add delete branch workflow
  .github/workflows/delete-branch.yml
Labels: feature
