Repository Coaktion/client-core, pull requests merged in 2023-11, with the labels that each got.

#59 feat: add code quality check
  .github/workflows/code_quality.yml
Labels: feature

#60 fix: fix zendesk makeRequest on catch
  .github/workflows/code_quality.yml
  src/zendesk.ts
Labels: bugfix

#61 chore(release): v1.5.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#62 Fix/axios retry condition
  package-lock.json
  package.json
  src/axios.ts
  src/base.ts
  src/types.ts
  tests/axios.test.ts
Labels: bugfix

#63 release: Adding release notes for v1.5.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#64 fix: make request params
  src/base.ts
  tests/base.test.ts
Labels: bugfix

#65 release/1.5.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#66 feat: add baseBearer auth class to share the logic of bearerToken pro…
  src/auth.ts
  src/types.ts
  tests/auth.test.ts
Labels: feature

#67 chore(release): v1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#68 feat: add get current ticket method to zendesk client
  src/zendesk.ts
  tests/zendesk.test.ts
Labels: feature

#69 chore: release v1.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#70 fix: get current ticket
  src/zendesk.ts
Labels: bugfix
